"""Prefect bridge — export orchestrate runs as Prefect flow files (Story 7.10).

Generates a standalone .py file that replicates the orchestration
as a Prefect flow with tasks and dependencies.
"""

from __future__ import annotations

import logging
import subprocess
import textwrap
from pathlib import Path
from typing import Any

from .epic_anchor import EpicSpec
from .orchestrator import OrchestrateReport, FORBIDDEN_VERBS, FORBIDDEN_PATHS

logger = logging.getLogger(__name__)


def export_prefect_flow(
    epic: EpicSpec,
    report: OrchestrateReport,
    output_path: Path,
) -> Path:
    """Write a Prefect flow .py file that replicates the orchestration.

    Args:
        epic: The epic specification
        report: The orchestration report (for wave structure)
        output_path: Where to write the flow file

    Returns:
        Path to the generated flow file
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build task definitions for each story
    task_defs = []
    task_names = {}

    for story in epic.stories:
        safe_name = f"story_{story.id.replace('.', '_')}"
        task_names[story.id] = safe_name

        deps = [
            task_names[d] for d in story.dependencies if d in task_names
        ]
        deps_str = f"[{', '.join(deps)}]" if deps else "[]"

        predicates = story.success_predicates or ["file_exists:README.md"]
        pred_list = ", ".join(f'"{p}"' for p in predicates)

        task_defs.append(textwrap.dedent(f'''\
            @task(name="story-{story.id}", retries=2)
            def {safe_name}() -> str:
                """Story {story.id}: {story.title}"""
                # Run implementation
                result = subprocess.run(
                    ["echo", "Executing story {story.id}: {story.title}"],
                    capture_output=True, text=True
                )
                # Evaluate predicates
                predicates = [{pred_list}]
                for pred in predicates:
                    if pred.startswith("file_exists:"):
                        path = pred.split(":", 1)[1].strip()
                        if not Path(path).exists():
                            raise FAIL(f"Predicate failed: {{pred}}")
                    elif not evaluate_predicate(pred):
                        raise FAIL(f"Predicate failed: {{pred}}")
                return "story {story.id} done"
        '''))

    # Build the flow function with dependency wiring
    flow_tasks = []
    for story in epic.stories:
        safe = task_names[story.id]
        deps = [task_names[d] for d in story.dependencies if d in task_names]
        if deps:
            dep_str = ", ".join(deps)
            flow_tasks.append(f'        {safe}_result = {safe}.submit(wait_for=[{dep_str}])')
        else:
            flow_tasks.append(f'        {safe}_result = {safe}.submit()')

    # Build wave summary for comments
    waves = report.waves if report.waves else epic.topological_waves()
    wave_comments = []
    for i, wave in enumerate(waves):
        wave_comments.append(f"# Wave {i}: {', '.join(wave)}")

    code = textwrap.dedent(f'''\
        """Prefect flow for Epic {epic.id}: {epic.name}

        Auto-generated by BMAD orchestrator.
        Replicates the wave-based execution from the orchestrate run.

        {chr(10).join(wave_comments)}
        """

        from __future__ import annotations

        import subprocess
        from pathlib import Path

        from prefect import flow, task
        from prefect.exceptions import PrefectException


        class FAIL(PrefectException):
            """Raised when a predicate fails."""
            pass


        def evaluate_predicate(pred: str) -> bool:
            """Evaluate a shell predicate (exit 0 = pass)."""
            try:
                result = subprocess.run(
                    ["bash", "-c", pred],
                    capture_output=True, text=True, timeout=60
                )
                return result.returncode == 0
            except Exception:
                return False


        {chr(10).join(task_defs)}

        @flow(name="epic-{epic.id}-{epic.name.lower().replace(' ', '-')}")
        def epic_{epic.id.replace('.', '_')}_flow():
            """Execute Epic {epic.id}: {epic.name}"""
        {chr(10).join(flow_tasks)}
            return "Epic {epic.id} complete"
    ''')

    output_path.write_text(code, encoding="utf-8")
    logger.info("[prefect] Exported flow to %s", output_path)
    return output_path


def launch_prefect(flow_path: Path) -> dict:
    """Run ``prefect deploy`` or ``prefect run`` on a generated flow.

    Args:
        flow_path: Path to the Prefect flow .py file

    Returns:
        Dict with status, stdout, stderr from the command
    """
    if not flow_path.exists():
        return {
            "status": "error",
            "error": f"Flow file not found: {flow_path}",
        }

    try:
        # Try 'prefect run' first (direct execution)
        result = subprocess.run(
            ["prefect", "run", str(flow_path)],
            capture_output=True,
            text=True,
            timeout=300,
            cwd=str(flow_path.parent),
        )
        return {
            "status": "success" if result.returncode == 0 else "error",
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }
    except FileNotFoundError:
        return {
            "status": "error",
            "error": "prefect CLI not found. Install with: pip install prefect",
        }
    except subprocess.TimeoutExpired:
        return {
            "status": "error",
            "error": "Prefect run timed out after 300s",
        }
    except Exception as exc:
        return {
            "status": "error",
            "error": f"Failed to launch Prefect: {exc}",
        }
